version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: clearvue-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./data/excel:/data/excel
    environment:
      - MONGO_INITDB_DATABASE=clearvue_db
    networks:
      - clearvue-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: clearvue-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper_data:/data
      - zookeeper_logs:/datalog
    networks:
      - clearvue-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: clearvue-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9021:9021"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    volumes:
      - kafka_data:/var/lib/kafka/data
    networks:
      - clearvue-network

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: clearvue-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:29092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
    networks:
      - clearvue-network

  data-ingestion:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: clearvue-data-ingestion
    depends_on:
      - mongodb
      - kafka
    volumes:
      - ./data/excel:/app/data/excel
      - ./scripts:/app/scripts
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/clearvue_db
      - KAFKA_BROKER=kafka:29092
    networks:
      - clearvue-network
    restart: on-failure
  
  payment-webhook:
    build:
      context: ./services/payment-webhook
      dockerfile: Dockerfile
    container_name: clearvue-payment-webhook
    ports:
      - "3000:3000"
    environment:
      - KAFKA_BROKER=kafka:29092
      - MONGODB_URI=mongodb://mongodb:27017/clearvue_db
    depends_on:
      - kafka
      - mongodb
    networks:
      - clearvue-network

volumes:
  mongodb_data:
  zookeeper_data:
  zookeeper_logs:
  kafka_data:

networks:
  clearvue-network:
    driver: bridge

